// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "Hoop":return img`
3 3 
3 3 
`;
            case "image3":
            case "Ball":return img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f f f . . . . 
. . . f f 4 4 f f f 4 4 f f . . 
. . f f 4 4 f f f f f 4 4 f f . 
. . f 4 4 f f 4 f 4 f f 4 4 f . 
. f 4 4 4 f 4 4 f 4 4 f 4 4 4 f 
. f 4 4 f 4 4 4 f 4 4 4 f 4 4 f 
. f f 4 f 4 4 4 f 4 4 4 f 4 f f 
. f f f f 4 4 4 f 4 4 4 f f f f 
. f 4 4 f f f f f f f f f 4 4 f 
. f 4 4 f 4 4 4 f 4 4 4 f 4 4 f 
. f 4 4 f f 4 4 f 4 4 f f 4 4 f 
. . f 4 4 f 4 4 f 4 4 f 4 4 f . 
. . f 4 4 f f 4 f 4 f f 4 4 f . 
. . . f f 4 f f f f f 4 f f . . 
. . . . . f 4 f f f 4 f . . . . 
`;
            case "image1":
            case "court":return img`
ddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddfffffffffffffffffffffffffdddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddfffffffffffffffffffffffffdddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddfffffffffffffffffffffffffdddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddfdddddddfdddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddddddddfdddddddddfddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddfdddddddddddfdddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddfdddddddddddfdddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddfdddddddddddfdddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddfdddddddddddfdddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddfdddddddddddfdddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddfdddddddddddfdddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddfdddddddddddfdddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddddddddfdddddddddfddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddfdddddddfdddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddddddddddfffffffddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddd222dddddd
ddddddd222ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddddddddddddddddddddddd2222dddddd
dddddddd22ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddddddddddddddddddddddd2222dddddd
dddddddd22ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddddddddddddddddddddddd222ddddddd
dddddddd22ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddd222dddddddd
dddddddd22ddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddd222dddddddd
dddddddd222dddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddd222dddddddd
dddddddd222dddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddd222dddddddd
dddddddd222dddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddd222dddddddd
dddddddd2222ddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddddddddddddddddddddd2222dddddddd
ddddddddd222ddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddddddddddddddddddddd222ddddddddd
ddddddddd2222dddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddddddddddddddddddddd222ddddddddd
ddddddddd2222dddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddddddddddddddddddddd222ddddddddd
ddddddddd2222dddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddddddddddddddddddddd222ddddddddd
ddddddddd22222ddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddd2222ddddddddd
dddddddddd2222ddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddd222dddddddddd
dddddddddd2222ddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddddddddddddddddddd2222dddddddddd
ddddddddddd2222dddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddddddddddddddddddd222ddddddddddd
ddddddddddd2222dddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddddddddddddddddddd222ddddddddddd
ddddddddddd22222ddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddd222dddddddddddd
dddddddddddd2222ddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddd222dddddddddddd
ddddddddddddd22222ddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddddddddddddddddd2222dddddddddddd
dddddddddddddd2222ddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddddddddddddddddd222ddddddddddddd
dddddddddddddd2222ddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddd2222ddddddddddddd
dddddddddddddd22222dddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddd222dddddddddddddd
ddddddddddddddd2222dddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddddddddddddddd2222dddddddddddddd
ddddddddddddddd2222dddddddddddddddddddddddddddddd222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddddddddddddddd222ddddddddddddddd
ddddddddddddddddd222ddddddddddddddddddddddddddddd222222222222222222222222222222222222222222222222222222222222222ddddddddddddddddddddddddddddd2222ddddddddddddddd
ddddddddddddddddd222ddddddddddddddddddddddddddddd222222222222222222222222222222222222222222222222222222222222222dddddddddddddddddddddddddddd222ddddddddddddddddd
ddddddddddddddddd2222dddddddddddddddddddddddddddd222222222222222222222222222222222222222222222222222222222222222dddddddddddddddddddddddddddd222ddddddddddddddddd
dddddddddddddddddd2222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd2222ddddddddddddddddd
dddddddddddddddddd22222dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddd
dddddddddddddddddddd222dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd22222dddddddddddddddddd
dddddddddddddddddddd2222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddddd
ddddddddddddddddddddd2222dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd22222dddddddddddddddddddd
ddddddddddddddddddddd22222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddddddd
ddddddddddddddddddddddd2222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd2222dddddddddddddddddddddd
ddddddddddddddddddddddd2222dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd2222ddddddddddddddddddddddd
dddddddddddddddddddddddd2222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd2222ddddddddddddddddddddddd
ddddddddddddddddddddddddd2222dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd22222dddddddddddddddddddddddd
ddddddddddddddddddddddddd222222dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddddddddddd
dddddddddddddddddddddddddddd22222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd2222dddddddddddddddddddddddddd
dddddddddddddddddddddddddddd222222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd2222ddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddd22222dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222222ddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddd22222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222dddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddd222222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd22222dddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddd222222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd2222dddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddd222222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222222dddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddd2222222dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd2222ddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddd22222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd22222ddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddd22222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd22222ddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddd2222222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd2222222ddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddd2222222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd2222222ddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddd2222222ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd2222222ddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddd22222222dddddddddddddddddddddddddddddddddddddddddddddddddddddddd222222dddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddd22222222dddddddddddddddddddddddddddddddddddddddddddddddddddd22222222dddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddd22222222dddddddddddddddddddddddddddddddddddddddddddddd222222222dddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddd222222222dddddddddddddddddddddddddddddddddddddddd2222222222dddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddd2222222222dddddddddddddddddddddddddddddddd222222222222dddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222222222222dddddddddddddddddddddd22222222222222ddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd222222222222222222222222222222222222222222ddddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd22222222222222222222222222222222222dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd2222222222222222222222222222dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
`;
            case "image5":
            case "p1Sprite":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f f f f f 4 4 f b f e f f . 
. f 4 f 4 4 f d d f 1 4 e e f . 
f 4 4 f 4 f f f d d d e e f . . 
4 4 4 f 4 f 4 4 f 4 e e f . . . 
f 4 4 f 4 f 4 4 f 2 2 f 4 e . . 
4 f f f f f f f f 2 2 f d 4 . . 
4 4 4 f 4 f 4 4 f 4 4 f 4 4 . . 
f 4 4 f 4 f 4 f f f f . . . . . 
. f f 4 f 4 f f . f f . . . . . 
`;
            case "image4":
            case "p2Ball":return img`
. . . . . f f 4 4 f f . . . . . 
. . . . f 5 4 5 5 4 5 f . . . . 
. . . f e 4 5 5 5 5 4 e f . . . 
. . f b 3 e 4 4 4 4 e 3 b f . . 
. . f 3 3 3 3 3 3 3 3 3 3 f . . 
. f 3 3 e b 3 e e 3 b e 3 3 f . 
. f 3 3 f f e e e e f f 3 3 f . 
. f f f f f f e e f b f b b f . 
. f 4 f 4 4 f f 4 f 1 e b b f . 
f 4 4 f 4 f 4 4 f 4 4 f b b f f 
f 4 4 f 4 f 4 4 f e f f f b b f 
f f 4 f 4 f 4 f f d b f e e f . 
f f f f f f f f f d d c 4 e . . 
f 4 4 f 4 f 4 4 f d b b f e . . 
f 4 4 f 4 4 f f d 1 d f f . . . 
. f f f f f f b b f f . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "song1":
            case "BullsTheme":return hex`00dc000408020206001c00010a006400f4016400000400000000000000000000000000000000020c0004002000010824004000010807001c00020a006400f40164000004000000000000000000000000000000000330000400080001220c00100001241400180001291c002000011d2400280001222c00300001243400380001273c004000011d`;
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
